---
kind: ClusterConfiguration
apiVersion: konvoy.mesosphere.io/v1alpha1
metadata:
  name: test75
  creationTimestamp: "2020-01-27T21:55:33.753550907Z"
spec:
  kubernetes:
    version: 1.15.3
    controlPlane:
      controlPlaneEndpointOverride: "147.75.107.32:6443"
      certificate: {}
      keepalived:
        enabled: true
        interface: bond0
    networking:
      podSubnet: 192.168.0.0/16
      serviceSubnet: 10.75.0.0/18
      httpProxy: ""
      httpsProxy: ""
    cloudProvider:
      provider: none
    admissionPlugins:
      enabled:
      - NodeRestriction
      - AlwaysPullImages
      disabled: []
    preflightChecks:
      errorsToIgnore: []
  containerNetworking:
    calico:
      version: v3.8.0
  containerRuntime:
    containerd:
      version: 1.2.6
      configData:
        data: ""
        replace: false
  packageRepository:
    defaultRepositoryInstallationDisabled: false
  nodePools:
  - name: worker
  addons:
    configVersion: stable-1.15.3-1
    addonsList:
    - name: dashboard
      enabled: true
    - name: dex
      enabled: true
    - name: dex-k8s-authenticator
      enabled: true
    - name: elasticsearch
      enabled: false
    - name: elasticsearchexporter
      enabled: false
    - name: fluentbit
      enabled: false
    - name: helm
      enabled: true
    - name: kibana
      enabled: false
    - name: kommander
      enabled: true
    - name: localvolumeprovisioner
      enabled: false
    - name: metallb
      enabled: true
      values: |-
        configInline:
          peers:
          - my-asn: 65000
            peer-asn: 65480
            peer-address: 127.0.0.1
          address-pools:
          - name: packet-public
            protocol: bgp
            addresses:
            - 147.75.107.32/32
    - name: opsportal
      enabled: true
    - name: prometheus
      enabled: false
    - name: prometheusadapter
      enabled: false
    - name: traefik
      enabled: true
    - name: traefik-forward-auth
      enabled: true
    - name: velero
      enabled: false
  version: v1.1.5

