---
kind: StoragePoolClaim
apiVersion: openebs.io/v1alpha1
metadata:
  name: cstor-stretched-claim
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
          memory: 2Gi
      - name: PoolResourceLimits
        value: |-
          memory: 4Gi
spec:
  name: cstor-stretched-claim
  type: disk
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList:
      - blockdevice-e7ce468b38ad829152ff01397302a101
      - blockdevice-353a6330fd1cba9b12f8747c14a5d47c
      - blockdevice-8cab95af164e58c51ed8f7f12f66fd17
      - blockdevice-1ef01d33b369d4dd133f443c1ff7df68
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cstor-stretched
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-stretched-claim"
      - name: ReplicaCount
        value: "3"
    storageclass.kubernetes.io/is-default-class: 'false'
provisioner: openebs.io/provisioner-iscsi
